INSERT INTO Paises (pais) VALUES ('Afganistán');
INSERT INTO Paises (pais) VALUES ('Albania');
INSERT INTO Paises (pais) VALUES ('Alemania');
INSERT INTO Paises (pais) VALUES ('Algeria');
INSERT INTO Paises (pais) VALUES ('Andorra');
INSERT INTO Paises (pais) VALUES ('Angola');
INSERT INTO Paises (pais) VALUES ('Anguila');
INSERT INTO Paises (pais) VALUES ('Antártida');
INSERT INTO Paises (pais) VALUES ('Antigua y Barbuda');
INSERT INTO Paises (pais) VALUES ('Antillas Neerlandesas');
INSERT INTO Paises (pais) VALUES ('Arabia Saudita');
INSERT INTO Paises (pais) VALUES ('Argentina');
INSERT INTO Paises (pais) VALUES ('Armenia');
INSERT INTO Paises (pais) VALUES ('Aruba');
INSERT INTO Paises (pais) VALUES ('Australia');
INSERT INTO Paises (pais) VALUES ('Austria');
INSERT INTO Paises (pais) VALUES ('Azerbayán');
INSERT INTO Paises (pais) VALUES ('Bélgica');
INSERT INTO Paises (pais) VALUES ('Bahamas');
INSERT INTO Paises (pais) VALUES ('Bahrein');
INSERT INTO Paises (pais) VALUES ('Bangladesh');
INSERT INTO Paises (pais) VALUES ('Barbados');
INSERT INTO Paises (pais) VALUES ('Belice');
INSERT INTO Paises (pais) VALUES ('Benín');
INSERT INTO Paises (pais) VALUES ('Bhután');
INSERT INTO Paises (pais) VALUES ('Bielorrusia');
INSERT INTO Paises (pais) VALUES ('Birmania');
INSERT INTO Paises (pais) VALUES ('Bolivia');
INSERT INTO Paises (pais) VALUES ('Bosnia y Herzegovina');
INSERT INTO Paises (pais) VALUES ('Botsuana');
INSERT INTO Paises (pais) VALUES ('Brasil');
INSERT INTO Paises (pais) VALUES ('Brunéi');
INSERT INTO Paises (pais) VALUES ('Bulgaria');
INSERT INTO Paises (pais) VALUES ('Burkina Faso');
INSERT INTO Paises (pais) VALUES ('Burundi');
INSERT INTO Paises (pais) VALUES ('Cabo Verde');
INSERT INTO Paises (pais) VALUES ('Camboya');
INSERT INTO Paises (pais) VALUES ('Camerún');
INSERT INTO Paises (pais) VALUES ('Canadá');
INSERT INTO Paises (pais) VALUES ('Chad');
INSERT INTO Paises (pais) VALUES ('Chile');
INSERT INTO Paises (pais) VALUES ('China');
INSERT INTO Paises (pais) VALUES ('Chipre');
INSERT INTO Paises (pais) VALUES ('Ciudad del Vaticano');
INSERT INTO Paises (pais) VALUES ('Colombia');
INSERT INTO Paises (pais) VALUES ('Comoras');
INSERT INTO Paises (pais) VALUES ('Congo');
INSERT INTO Paises (pais) VALUES ('Congo');
INSERT INTO Paises (pais) VALUES ('Corea del Norte');
INSERT INTO Paises (pais) VALUES ('Corea del Sur');
INSERT INTO Paises (pais) VALUES ('Costa de Marfil');
INSERT INTO Paises (pais) VALUES ('Costa Rica');
INSERT INTO Paises (pais) VALUES ('Croacia');
INSERT INTO Paises (pais) VALUES ('Cuba');
INSERT INTO Paises (pais) VALUES ('Dinamarca');
INSERT INTO Paises (pais) VALUES ('Dominica');
INSERT INTO Paises (pais) VALUES ('Ecuador');
INSERT INTO Paises (pais) VALUES ('Egipto');
INSERT INTO Paises (pais) VALUES ('El Salvador');
INSERT INTO Paises (pais) VALUES ('Emiratos Árabes Unidos');
INSERT INTO Paises (pais) VALUES ('Eritrea');
INSERT INTO Paises (pais) VALUES ('Eslovaquia');
INSERT INTO Paises (pais) VALUES ('Eslovenia');
INSERT INTO Paises (pais) VALUES ('España');
INSERT INTO Paises (pais) VALUES ('Estados Unidos de América');
INSERT INTO Paises (pais) VALUES ('Estonia');
INSERT INTO Paises (pais) VALUES ('Etiopía');
INSERT INTO Paises (pais) VALUES ('Filipinas');
INSERT INTO Paises (pais) VALUES ('Finlandia');
INSERT INTO Paises (pais) VALUES ('Fiyi');
INSERT INTO Paises (pais) VALUES ('Francia');
INSERT INTO Paises (pais) VALUES ('Gabón');
INSERT INTO Paises (pais) VALUES ('Gambia');
INSERT INTO Paises (pais) VALUES ('Georgia');
INSERT INTO Paises (pais) VALUES ('Ghana');
INSERT INTO Paises (pais) VALUES ('Gibraltar');
INSERT INTO Paises (pais) VALUES ('Granada');
INSERT INTO Paises (pais) VALUES ('Grecia');
INSERT INTO Paises (pais) VALUES ('Groenlandia');
INSERT INTO Paises (pais) VALUES ('Guadalupe');
INSERT INTO Paises (pais) VALUES ('Guam');
INSERT INTO Paises (pais) VALUES ('Guatemala');
INSERT INTO Paises (pais) VALUES ('Guayana Francesa');
INSERT INTO Paises (pais) VALUES ('Guernsey');
INSERT INTO Paises (pais) VALUES ('Guinea');
INSERT INTO Paises (pais) VALUES ('Guinea Ecuatorial');
INSERT INTO Paises (pais) VALUES ('Guinea-Bissau');
INSERT INTO Paises (pais) VALUES ('Guyana');
INSERT INTO Paises (pais) VALUES ('Haití');
INSERT INTO Paises (pais) VALUES ('Honduras');
INSERT INTO Paises (pais) VALUES ('Hong kong');
INSERT INTO Paises (pais) VALUES ('Hungría');
INSERT INTO Paises (pais) VALUES ('India');
INSERT INTO Paises (pais) VALUES ('Indonesia');
INSERT INTO Paises (pais) VALUES ('Irán');
INSERT INTO Paises (pais) VALUES ('Irak');
INSERT INTO Paises (pais) VALUES ('Irlanda');
INSERT INTO Paises (pais) VALUES ('Isla Bouvet');
INSERT INTO Paises (pais) VALUES ('Isla de Man');
INSERT INTO Paises (pais) VALUES ('Isla de Navidad');
INSERT INTO Paises (pais) VALUES ('Isla Norfolk');
INSERT INTO Paises (pais) VALUES ('Islandia');
INSERT INTO Paises (pais) VALUES ('Islas Bermudas');
INSERT INTO Paises (pais) VALUES ('Islas Caimán');
INSERT INTO Paises (pais) VALUES ('Islas Cocos (Keeling)');
INSERT INTO Paises (pais) VALUES ('Islas Cook');
INSERT INTO Paises (pais) VALUES ('Islas de Åland');
INSERT INTO Paises (pais) VALUES ('Islas Feroe');
INSERT INTO Paises (pais) VALUES ('Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO Paises (pais) VALUES ('Islas Heard y McDonald');
INSERT INTO Paises (pais) VALUES ('Islas Maldivas');
INSERT INTO Paises (pais) VALUES ('Islas Malvinas');
INSERT INTO Paises (pais) VALUES ('Islas Marianas del Norte');
INSERT INTO Paises (pais) VALUES ('Islas Marshall');
INSERT INTO Paises (pais) VALUES ('Islas Pitcairn');
INSERT INTO Paises (pais) VALUES ('Islas Salomón');
INSERT INTO Paises (pais) VALUES ('Islas Turcas y Caicos');
INSERT INTO Paises (pais) VALUES ('Islas Ultramarinas Menores de Estados Unidos');
INSERT INTO Paises (pais) VALUES ('Islas Vírgenes Británicas');
INSERT INTO Paises (pais) VALUES ('Islas Vírgenes de los Estados Unidos');
INSERT INTO Paises (pais) VALUES ('Israel');
INSERT INTO Paises (pais) VALUES ('Italia');
INSERT INTO Paises (pais) VALUES ('Jamaica');
INSERT INTO Paises (pais) VALUES ('Japón');
INSERT INTO Paises (pais) VALUES ('Jersey');
INSERT INTO Paises (pais) VALUES ('Jordania');
INSERT INTO Paises (pais) VALUES ('Kazajistán');
INSERT INTO Paises (pais) VALUES ('Kenia');
INSERT INTO Paises (pais) VALUES ('Kirgizstán');
INSERT INTO Paises (pais) VALUES ('Kiribati');
INSERT INTO Paises (pais) VALUES ('Kuwait');
INSERT INTO Paises (pais) VALUES ('Líbano');
INSERT INTO Paises (pais) VALUES ('Laos');
INSERT INTO Paises (pais) VALUES ('Lesoto');
INSERT INTO Paises (pais) VALUES ('Letonia');
INSERT INTO Paises (pais) VALUES ('Liberia');
INSERT INTO Paises (pais) VALUES ('Libia');
INSERT INTO Paises (pais) VALUES ('Liechtenstein');
INSERT INTO Paises (pais) VALUES ('Lituania');
INSERT INTO Paises (pais) VALUES ('Luxemburgo');
INSERT INTO Paises (pais) VALUES ('México');
INSERT INTO Paises (pais) VALUES ('Mónaco');
INSERT INTO Paises (pais) VALUES ('Macao');
INSERT INTO Paises (pais) VALUES ('Macedônia');
INSERT INTO Paises (pais) VALUES ('Madagascar');
INSERT INTO Paises (pais) VALUES ('Malasia');
INSERT INTO Paises (pais) VALUES ('Malawi');
INSERT INTO Paises (pais) VALUES ('Mali');
INSERT INTO Paises (pais) VALUES ('Malta');
INSERT INTO Paises (pais) VALUES ('Marruecos');
INSERT INTO Paises (pais) VALUES ('Martinica');
INSERT INTO Paises (pais) VALUES ('Mauricio');
INSERT INTO Paises (pais) VALUES ('Mauritania');
INSERT INTO Paises (pais) VALUES ('Mayotte');
INSERT INTO Paises (pais) VALUES ('Micronesia');
INSERT INTO Paises (pais) VALUES ('Moldavia');
INSERT INTO Paises (pais) VALUES ('Mongolia');
INSERT INTO Paises (pais) VALUES ('Montenegro');
INSERT INTO Paises (pais) VALUES ('Montserrat');
INSERT INTO Paises (pais) VALUES ('Mozambique');
INSERT INTO Paises (pais) VALUES ('Namibia');
INSERT INTO Paises (pais) VALUES ('Nauru');
INSERT INTO Paises (pais) VALUES ('Nepal');
INSERT INTO Paises (pais) VALUES ('Nicaragua');
INSERT INTO Paises (pais) VALUES ('Niger');
INSERT INTO Paises (pais) VALUES ('Nigeria');
INSERT INTO Paises (pais) VALUES ('Niue');
INSERT INTO Paises (pais) VALUES ('Noruega');
INSERT INTO Paises (pais) VALUES ('Nueva Caledonia');
INSERT INTO Paises (pais) VALUES ('Nueva Zelanda');
INSERT INTO Paises (pais) VALUES ('Omán');
INSERT INTO Paises (pais) VALUES ('Países Bajos');
INSERT INTO Paises (pais) VALUES ('Pakistán');
INSERT INTO Paises (pais) VALUES ('Palau');
INSERT INTO Paises (pais) VALUES ('Palestina');
INSERT INTO Paises (pais) VALUES ('Panamá');
INSERT INTO Paises (pais) VALUES ('Papúa Nueva Guinea');
INSERT INTO Paises (pais) VALUES ('Paraguay');
INSERT INTO Paises (pais) VALUES ('Perú');
INSERT INTO Paises (pais) VALUES ('Polinesia Francesa');
INSERT INTO Paises (pais) VALUES ('Polonia');
INSERT INTO Paises (pais) VALUES ('Portugal');
INSERT INTO Paises (pais) VALUES ('Puerto Rico');
INSERT INTO Paises (pais) VALUES ('Qatar');
INSERT INTO Paises (pais) VALUES ('Reino Unido');
INSERT INTO Paises (pais) VALUES ('República Centroafricana');
INSERT INTO Paises (pais) VALUES ('República Checa');
INSERT INTO Paises (pais) VALUES ('República Dominicana');
INSERT INTO Paises (pais) VALUES ('Reunión');
INSERT INTO Paises (pais) VALUES ('Ruanda');
INSERT INTO Paises (pais) VALUES ('Rumanía');
INSERT INTO Paises (pais) VALUES ('Rusia');
INSERT INTO Paises (pais) VALUES ('Sahara Occidental');
INSERT INTO Paises (pais) VALUES ('Samoa');
INSERT INTO Paises (pais) VALUES ('Samoa Americana');
INSERT INTO Paises (pais) VALUES ('San Bartolomé');
INSERT INTO Paises (pais) VALUES ('San Cristóbal y Nieves');
INSERT INTO Paises (pais) VALUES ('San Marino');
INSERT INTO Paises (pais) VALUES ('San Martín (Francia)');
INSERT INTO Paises (pais) VALUES ('San Pedro y Miquelón');
INSERT INTO Paises (pais) VALUES ('San Vicente y las Granadinas');
INSERT INTO Paises (pais) VALUES ('Santa Elena');
INSERT INTO Paises (pais) VALUES ('Santa Lucía');
INSERT INTO Paises (pais) VALUES ('Santo Tomé y Príncipe');
INSERT INTO Paises (pais) VALUES ('Senegal');
INSERT INTO Paises (pais) VALUES ('Serbia');
INSERT INTO Paises (pais) VALUES ('Seychelles');
INSERT INTO Paises (pais) VALUES ('Sierra Leona');
INSERT INTO Paises (pais) VALUES ('Singapur');
INSERT INTO Paises (pais) VALUES ('Siria');
INSERT INTO Paises (pais) VALUES ('Somalia');
INSERT INTO Paises (pais) VALUES ('Sri lanka');
INSERT INTO Paises (pais) VALUES ('Sudáfrica');
INSERT INTO Paises (pais) VALUES ('Sudán');
INSERT INTO Paises (pais) VALUES ('Suecia');
INSERT INTO Paises (pais) VALUES ('Suiza');
INSERT INTO Paises (pais) VALUES ('Surinám');
INSERT INTO Paises (pais) VALUES ('Svalbard y Jan Mayen');
INSERT INTO Paises (pais) VALUES ('Swazilandia');
INSERT INTO Paises (pais) VALUES ('Tadjikistán');
INSERT INTO Paises (pais) VALUES ('Tailandia');
INSERT INTO Paises (pais) VALUES ('Taiwán');
INSERT INTO Paises (pais) VALUES ('Tanzania');
INSERT INTO Paises (pais) VALUES ('Territorio Británico del Océano Índico');
INSERT INTO Paises (pais) VALUES ('Territorios Australes y Antárticas Franceses');
INSERT INTO Paises (pais) VALUES ('Timor Oriental');
INSERT INTO Paises (pais) VALUES ('Togo');
INSERT INTO Paises (pais) VALUES ('Tokelau');
INSERT INTO Paises (pais) VALUES ('Tonga');
INSERT INTO Paises (pais) VALUES ('Trinidad y Tobago');
INSERT INTO Paises (pais) VALUES ('Tunez');
INSERT INTO Paises (pais) VALUES ('Turkmenistán');
INSERT INTO Paises (pais) VALUES ('Turquía');
INSERT INTO Paises (pais) VALUES ('Tuvalu');
INSERT INTO Paises (pais) VALUES ('Ucrania');
INSERT INTO Paises (pais) VALUES ('Uganda');
INSERT INTO Paises (pais) VALUES ('Uruguay');
INSERT INTO Paises (pais) VALUES ('Uzbekistán');
INSERT INTO Paises (pais) VALUES ('Vanuatu');
INSERT INTO Paises (pais) VALUES ('Venezuela');
INSERT INTO Paises (pais) VALUES ('Vietnam');
INSERT INTO Paises (pais) VALUES ('Wallis y Futuna');
INSERT INTO Paises (pais) VALUES ('Yemen');
INSERT INTO Paises (pais) VALUES ('Yibuti');
INSERT INTO Paises (pais) VALUES ('Zambia');
INSERT INTO Paises (pais) VALUES ('Zimbabue');
