INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Buenos Aires');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Buenos Aires-GBA');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Capital Federal');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Catamarca');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Chaco');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Chubut');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Córdoba');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Corrientes');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Entre Ríos');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Formosa');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Jujuy');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'La Pampa');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'La Rioja');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Mendoza');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Misiones');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Neuquén');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Río Negro');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Salta');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'San Juan');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'San Luis');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Santa Cruz');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Santa Fe');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Santiago del Estero');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Tierra del Fuego');
INSERT INTO Provincias(codPais,provincia) VALUES (12,   'Tucumán');
